import { AchievementDefinition } from './types';

export const ACHIEVEMENTS: AchievementDefinition[] = [
  // ── Solo Pomodoro Milestones ────────────────────────────────────────────
  {
    id: 'first-step',
    name: 'First Step',
    emoji: '🍅',
    description: 'Complete your very first pomodoro.',
    hint: 'Start a timer and see it through.',
    category: 'solo',
    tier: 'bronze',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'Your first pomodoro is in the books. The journey of a thousand sessions begins here.',
  },
  {
    id: 'finding-your-rhythm',
    name: 'Finding Your Rhythm',
    emoji: '🎵',
    description: 'Complete 10 pomodoros.',
    hint: 'Keep showing up. Ten times.',
    category: 'solo',
    tier: 'bronze',
    isSecret: false,
    progressType: 'count',
    progressTarget: 10,
    toastCopy: 'Ten sessions down. You\'re starting to find your groove.',
  },
  {
    id: 'centurion',
    name: 'Centurion',
    emoji: '💯',
    description: 'Complete 100 pomodoros.',
    hint: 'A hundred sessions of focused work.',
    category: 'solo',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 100,
    toastCopy: '100 sessions. That\'s over 40 hours of focused work. Centurion status earned.',
  },
  {
    id: 'pomodoro-pro',
    name: 'Pomodoro Pro',
    emoji: '⭐',
    description: 'Complete 500 pomodoros.',
    hint: 'Five hundred sessions. Rare company.',
    category: 'solo',
    tier: 'gold',
    isSecret: false,
    progressType: 'count',
    progressTarget: 500,
    toastCopy: '500 sessions. Most people never get here. You\'re not most people.',
  },
  {
    id: 'the-legend',
    name: 'The Legend',
    emoji: '👑',
    description: 'Complete 1,000 pomodoros.',
    hint: 'A thousand sessions. Legendary status.',
    category: 'solo',
    tier: 'platinum',
    isSecret: false,
    progressType: 'count',
    progressTarget: 1000,
    toastCopy: '1,000 sessions. That\'s roughly 417 hours of focused work. Legendary.',
  },
  {
    id: 'long-haul',
    name: 'Long Haul',
    emoji: '🏃',
    description: 'Complete 4 consecutive pomodoros in one sitting without resetting the timer.',
    hint: 'Four in a row without breaking the chain.',
    category: 'solo',
    tier: 'bronze',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'Four in a row. That\'s a two-hour focus block. You were locked in.',
  },
  {
    id: 'marathon-runner',
    name: 'Marathon Runner',
    emoji: '🏅',
    description: 'Complete 8 consecutive pomodoros in one sitting.',
    hint: 'Eight in a row. The long game.',
    category: 'solo',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 8,
    toastCopy: 'Eight pomodoros back-to-back. That\'s a marathon session. Hope you stood up at some point.',
  },
  {
    id: 'ultramarathon',
    name: 'Ultramarathon',
    emoji: '🦅',
    description: 'Complete 12 consecutive pomodoros in one sitting — a full 6-hour focus block.',
    hint: 'Twelve in a row. A six-hour sitting.',
    category: 'solo',
    tier: 'gold',
    isSecret: false,
    progressType: 'count',
    progressTarget: 12,
    toastCopy: 'Twelve. Six hours. We\'re a little concerned about you, but also very impressed.',
  },
  {
    id: 'flow-state',
    name: 'Flow State',
    emoji: '🌊',
    description: 'Complete 8 work sessions in a single calendar day.',
    hint: 'Eight sessions in one day.',
    category: 'solo',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 8,
    toastCopy: 'Eight sessions in a day. You found the zone. Don\'t lose it.',
  },
  {
    id: 'the-grind',
    name: 'The Grind',
    emoji: '⚙️',
    description: 'Complete 12 work sessions in a single calendar day.',
    hint: 'Twelve sessions in one day.',
    category: 'solo',
    tier: 'gold',
    isSecret: false,
    progressType: 'count',
    progressTarget: 12,
    toastCopy: 'Twelve sessions in a day. Whatever you\'re working on, we hope it was worth it.',
  },
  {
    id: 'custom-craftsman',
    name: 'Custom Craftsman',
    emoji: '🔧',
    description: 'Complete a pomodoro with non-default timer settings.',
    hint: 'Try adjusting your timer duration.',
    category: 'solo',
    tier: 'bronze',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'You found the settings menu. PomoPals works your way now.',
  },
  // ── Social & Friends ────────────────────────────────────────────────────
  {
    id: 'social-spark',
    name: 'Social Spark',
    emoji: '✨',
    description: 'Add your first friend.',
    hint: 'Connect with another PomoPals user.',
    category: 'social',
    tier: 'bronze',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'Your first PomoPals friend. Focus is better together.',
  },
  {
    id: 'building-your-circle',
    name: 'Building Your Circle',
    emoji: '👥',
    description: 'Have 5 confirmed friends.',
    hint: 'Build a focus crew of five.',
    category: 'social',
    tier: 'bronze',
    isSecret: false,
    progressType: 'count',
    progressTarget: 5,
    toastCopy: 'Five friends. Your focus crew is taking shape.',
  },
  {
    id: 'the-connector',
    name: 'The Connector',
    emoji: '🌐',
    description: 'Have 25 confirmed friends.',
    hint: 'Grow your focus network to twenty-five.',
    category: 'social',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 25,
    toastCopy: '25 friends. You\'re building a real community around focus. That matters.',
  },
  {
    id: 'open-door',
    name: 'Open Door',
    emoji: '🚪',
    description: 'Create your first room.',
    hint: 'Open a room for others to join.',
    category: 'social',
    tier: 'bronze',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'Your first room is open. Invite someone — focus is contagious.',
  },
  {
    id: 'gracious-host',
    name: 'Gracious Host',
    emoji: '🏠',
    description: 'Host 10 rooms.',
    hint: 'Keep opening the door for others.',
    category: 'social',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 10,
    toastCopy: 'Ten rooms hosted. You keep showing up for others. That\'s what makes a good host.',
  },
  {
    id: 'grand-host',
    name: 'Grand Host',
    emoji: '🏛️',
    description: 'Host 50 rooms.',
    hint: 'Fifty rooms. An extraordinary host.',
    category: 'social',
    tier: 'gold',
    isSecret: false,
    progressType: 'count',
    progressTarget: 50,
    toastCopy: '50 rooms. You\'ve created thousands of minutes of shared focus. Grand.',
  },
  {
    id: 'joining-in',
    name: 'Joining In',
    emoji: '🤝',
    description: 'Join a room created by one of your friends for the first time.',
    hint: 'Step into a friend\'s focus room.',
    category: 'social',
    tier: 'bronze',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'You joined a friend\'s room. Now you\'re really doing this together.',
  },
  {
    id: 'better-together',
    name: 'Better Together',
    emoji: '💪',
    description: 'Complete a work session in a room with at least 3 participants total.',
    hint: 'Focus with two others in the same room.',
    category: 'social',
    tier: 'bronze',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'Three people, one goal. Better together is right.',
  },
  {
    id: 'squad-goals',
    name: 'Squad Goals',
    emoji: '🎯',
    description: 'Complete a work session in a room with 5 or more participants.',
    hint: 'Five or more people in one room.',
    category: 'social',
    tier: 'silver',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'A five-person focus session. That\'s a squad.',
  },
  {
    id: 'pack-leader',
    name: 'Pack Leader',
    emoji: '🐺',
    description: 'Host a room that reaches 10 or more simultaneous participants.',
    hint: 'Fill your hosted room with ten people.',
    category: 'social',
    tier: 'gold',
    isSecret: false,
    progressType: 'count',
    progressTarget: 10,
    toastCopy: 'Ten people followed your lead. That\'s a pack.',
  },
  {
    id: 'full-house',
    name: 'Full House',
    emoji: '🎪',
    description: 'Fill a room you\'re hosting to its 20-person capacity.',
    hint: 'Pack a hosted room to the absolute limit.',
    category: 'social',
    tier: 'platinum',
    isSecret: false,
    progressType: 'count',
    progressTarget: 20,
    toastCopy: 'Maximum capacity. Twenty people, one room, one focus session. Full house.',
  },
  // ── Consistency ─────────────────────────────────────────────────────────
  {
    id: 'habit-forming',
    name: 'Habit Forming',
    emoji: '🔥',
    description: 'Focus on 3 consecutive calendar days.',
    hint: 'Show up three days in a row.',
    category: 'consistency',
    tier: 'bronze',
    isSecret: false,
    progressType: 'count',
    progressTarget: 3,
    toastCopy: 'Three days in a row. A habit is starting to form.',
  },
  {
    id: 'week-in-the-zone',
    name: 'Week in the Zone',
    emoji: '📅',
    description: 'Focus every day for 7 consecutive calendar days.',
    hint: 'Don\'t miss a single day for a week.',
    category: 'consistency',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 7,
    toastCopy: 'Seven days straight. You\'ve completed your first week. That\'s no accident.',
  },
  {
    id: 'unbreakable',
    name: 'Unbreakable',
    emoji: '💎',
    description: 'Maintain a 30-day streak.',
    hint: 'Thirty days without missing one.',
    category: 'consistency',
    tier: 'gold',
    isSecret: false,
    progressType: 'count',
    progressTarget: 30,
    toastCopy: 'Thirty days without missing one. You built something real.',
  },
  {
    id: 'centurion-streak',
    name: 'Centurion Streak',
    emoji: '🌟',
    description: 'Maintain a 100-day streak.',
    hint: 'One hundred consecutive days of focus.',
    category: 'consistency',
    tier: 'platinum',
    isSecret: false,
    progressType: 'count',
    progressTarget: 100,
    toastCopy: 'One hundred days. Whatever you\'re working on, you\'re going to finish it.',
  },
  {
    id: 'creature-of-habit',
    name: 'Creature of Habit',
    emoji: '⏰',
    description: 'Complete sessions in the same 2-hour window for 10 different days.',
    hint: 'Work at the same time, day after day.',
    category: 'consistency',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 10,
    toastCopy: 'Same time, ten different days. Your brain knows when it\'s time to work.',
  },
  {
    id: 'weekend-warrior',
    name: 'Weekend Warrior',
    emoji: '⚔️',
    description: 'Complete 5 pomodoros on a single Saturday or Sunday.',
    hint: 'Five sessions on a weekend day.',
    category: 'consistency',
    tier: 'bronze',
    isSecret: false,
    progressType: 'count',
    progressTarget: 5,
    toastCopy: 'Five sessions on a weekend. Your future self thanks you.',
  },
  {
    id: 'perfect-week',
    name: 'Perfect Week',
    emoji: '✅',
    description: 'Complete at least 4 pomodoros every day for 7 consecutive days.',
    hint: 'Four or more sessions, every day, for a week.',
    category: 'consistency',
    tier: 'gold',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'Four or more, every single day, for seven days. That\'s not a week — that\'s a statement.',
  },
  {
    id: 'study-buddy',
    name: 'Study Buddy',
    emoji: '📚',
    description: 'Complete a pomodoro in a room with the same friend on 5 different calendar days.',
    hint: 'Focus alongside the same friend, repeatedly.',
    category: 'consistency',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 5,
    toastCopy: 'Five days focusing alongside the same friend. You two make a good team.',
  },
  // ── Easter Eggs ─────────────────────────────────────────────────────────
  {
    id: 'pomversary',
    name: 'Pomversary',
    emoji: '🎂',
    description: 'Complete a pomodoro within 7 days of your 1-year account anniversary.',
    hint: 'Mark your PomoPals anniversary with a session.',
    category: 'easter_egg',
    tier: 'gold',
    isSecret: true,
    progressType: 'binary',
    toastCopy: 'One year with PomoPals. Whatever you\'ve been building — you\'ve been building it for a year now.',
  },
  {
    id: 'back-from-the-dead',
    name: 'Back From the Dead',
    emoji: '💀',
    description: 'Return to PomoPals after 30+ days away and complete a pomodoro.',
    hint: 'Coming back after a long break.',
    category: 'easter_egg',
    tier: 'silver',
    isSecret: true,
    progressType: 'binary',
    toastCopy: 'Thirty days away. But here you are. Welcome back — the timer was waiting.',
  },
];

export const ACHIEVEMENT_MAP = new Map<string, AchievementDefinition>(
  ACHIEVEMENTS.map((a) => [a.id, a])
);
