import { AchievementDefinition } from './types';

export const ACHIEVEMENTS: AchievementDefinition[] = [
  // ── Solo Pomodoro Milestones ────────────────────────────────────────────
  {
    id: 'first-step',
    name: 'First Step',
    emoji: '🍅',
    description: 'Complete 1 pomodoro (any duration).',
    hint: 'Complete 1 pomodoro (any duration).',
    category: 'solo',
    tier: 'bronze',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'Your first pomodoro is in the books. The journey of a thousand sessions begins here.',
  },
  {
    id: 'finding-your-rhythm',
    name: 'Finding Your Rhythm',
    emoji: '🎵',
    description: 'Complete 10 total pomodoros.',
    hint: 'Complete 10 total pomodoros.',
    category: 'solo',
    tier: 'bronze',
    isSecret: false,
    progressType: 'count',
    progressTarget: 10,
    toastCopy: 'Ten sessions down. You\'re starting to find your groove.',
  },
  {
    id: 'centurion',
    name: 'Centurion',
    emoji: '💯',
    description: 'Complete 100 total pomodoros.',
    hint: 'Complete 100 total pomodoros.',
    category: 'solo',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 100,
    toastCopy: '100 sessions. That\'s over 40 hours of focused work. Centurion status earned.',
  },
  {
    id: 'pomodoro-pro',
    name: 'Pomodoro Pro',
    emoji: '⭐',
    description: 'Complete 500 total pomodoros.',
    hint: 'Complete 500 total pomodoros.',
    category: 'solo',
    tier: 'gold',
    isSecret: false,
    progressType: 'count',
    progressTarget: 500,
    toastCopy: '500 sessions. Most people never get here. You\'re not most people.',
  },
  {
    id: 'the-legend',
    name: 'The Legend',
    emoji: '👑',
    description: 'Complete 1,000 total pomodoros.',
    hint: 'Complete 1,000 total pomodoros.',
    category: 'solo',
    tier: 'platinum',
    isSecret: false,
    progressType: 'count',
    progressTarget: 1000,
    toastCopy: '1,000 sessions. That\'s roughly 417 hours of focused work. Legendary.',
  },
  {
    id: 'long-haul',
    name: 'Long Haul',
    emoji: '🏃',
    description: 'Complete 4 pomodoros in a row without resetting (same sitting).',
    hint: 'Complete 4 pomodoros in a row without resetting (same sitting).',
    category: 'solo',
    tier: 'bronze',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'Four in a row. That\'s a two-hour focus block. You were locked in.',
  },
  {
    id: 'marathon-runner',
    name: 'Marathon Runner',
    emoji: '🏅',
    description: 'Complete 8 pomodoros in a row without resetting (same sitting).',
    hint: 'Complete 8 pomodoros in a row without resetting (same sitting).',
    category: 'solo',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 8,
    toastCopy: 'Eight pomodoros back-to-back. That\'s a marathon session. Hope you stood up at some point.',
  },
  {
    id: 'ultramarathon',
    name: 'Ultramarathon',
    emoji: '🦅',
    description: 'Complete 12 pomodoros in a row without resetting (same sitting, ~6 hours).',
    hint: 'Complete 12 pomodoros in a row without resetting (same sitting, ~6 hours).',
    category: 'solo',
    tier: 'gold',
    isSecret: false,
    progressType: 'count',
    progressTarget: 12,
    toastCopy: 'Twelve. Six hours. We\'re a little concerned about you, but also very impressed.',
  },
  {
    id: 'flow-state',
    name: 'Flow State',
    emoji: '🌊',
    description: 'Complete 8 pomodoros in a single calendar day.',
    hint: 'Complete 8 pomodoros in a single calendar day.',
    category: 'solo',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 8,
    toastCopy: 'Eight sessions in a day. You found the zone. Don\'t lose it.',
  },
  {
    id: 'the-grind',
    name: 'The Grind',
    emoji: '⚙️',
    description: 'Complete 12 pomodoros in a single calendar day.',
    hint: 'Complete 12 pomodoros in a single calendar day.',
    category: 'solo',
    tier: 'gold',
    isSecret: false,
    progressType: 'count',
    progressTarget: 12,
    toastCopy: 'Twelve sessions in a day. Whatever you\'re working on, we hope it was worth it.',
  },
  {
    id: 'custom-craftsman',
    name: 'Custom Craftsman',
    emoji: '🔧',
    description: 'Complete 1 pomodoro with a non-default timer duration (not 25 min).',
    hint: 'Complete 1 pomodoro with a non-default timer duration (not 25 min).',
    category: 'solo',
    tier: 'bronze',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'You found the settings menu. PomoPals works your way now.',
  },
  // ── Social & Friends ────────────────────────────────────────────────────
  {
    id: 'social-spark',
    name: 'Social Spark',
    emoji: '✨',
    description: 'Have 1 confirmed friend on PomoPals.',
    hint: 'Have 1 confirmed friend on PomoPals.',
    category: 'social',
    tier: 'bronze',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'Your first PomoPals friend. Focus is better together.',
  },
  {
    id: 'building-your-circle',
    name: 'Building Your Circle',
    emoji: '👥',
    description: 'Have 5 confirmed friends on PomoPals.',
    hint: 'Have 5 confirmed friends on PomoPals.',
    category: 'social',
    tier: 'bronze',
    isSecret: false,
    progressType: 'count',
    progressTarget: 5,
    toastCopy: 'Five friends. Your focus crew is taking shape.',
  },
  {
    id: 'the-connector',
    name: 'The Connector',
    emoji: '🌐',
    description: 'Have 25 confirmed friends on PomoPals.',
    hint: 'Have 25 confirmed friends on PomoPals.',
    category: 'social',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 25,
    toastCopy: '25 friends. You\'re building a real community around focus. That matters.',
  },
  {
    id: 'open-door',
    name: 'Open Door',
    emoji: '🚪',
    description: 'Create 1 room using the Create Room button.',
    hint: 'Create 1 room using the Create Room button.',
    category: 'social',
    tier: 'bronze',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'Your first room is open. Invite someone — focus is contagious.',
  },
  {
    id: 'gracious-host',
    name: 'Gracious Host',
    emoji: '🏠',
    description: 'Create 10 rooms total.',
    hint: 'Create 10 rooms total.',
    category: 'social',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 10,
    toastCopy: 'Ten rooms hosted. You keep showing up for others. That\'s what makes a good host.',
  },
  {
    id: 'grand-host',
    name: 'Grand Host',
    emoji: '🏛️',
    description: 'Create 50 rooms total.',
    hint: 'Create 50 rooms total.',
    category: 'social',
    tier: 'gold',
    isSecret: false,
    progressType: 'count',
    progressTarget: 50,
    toastCopy: '50 rooms. You\'ve created thousands of minutes of shared focus. Grand.',
  },
  {
    id: 'joining-in',
    name: 'Joining In',
    emoji: '🤝',
    description: 'Join a room hosted by someone on your friends list.',
    hint: 'Join a room hosted by someone on your friends list.',
    category: 'social',
    tier: 'bronze',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'You joined a friend\'s room. Now you\'re really doing this together.',
  },
  {
    id: 'better-together',
    name: 'Better Together',
    emoji: '💪',
    description: 'Finish a pomodoro in a room with 3 or more people present.',
    hint: 'Finish a pomodoro in a room with 3 or more people present.',
    category: 'social',
    tier: 'bronze',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'Three people, one goal. Better together is right.',
  },
  {
    id: 'squad-goals',
    name: 'Squad Goals',
    emoji: '🎯',
    description: 'Finish a pomodoro in a room with 5 or more people present.',
    hint: 'Finish a pomodoro in a room with 5 or more people present.',
    category: 'social',
    tier: 'silver',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'A five-person focus session. That\'s a squad.',
  },
  {
    id: 'pack-leader',
    name: 'Pack Leader',
    emoji: '🐺',
    description: 'Host a room that has 10 or more people in it at the same time.',
    hint: 'Host a room that has 10 or more people in it at the same time.',
    category: 'social',
    tier: 'gold',
    isSecret: false,
    progressType: 'count',
    progressTarget: 10,
    toastCopy: 'Ten people followed your lead. That\'s a pack.',
  },
  {
    id: 'full-house',
    name: 'Full House',
    emoji: '🎪',
    description: 'Host a room that reaches the 20-person maximum capacity.',
    hint: 'Host a room that reaches the 20-person maximum capacity.',
    category: 'social',
    tier: 'platinum',
    isSecret: false,
    progressType: 'count',
    progressTarget: 20,
    toastCopy: 'Maximum capacity. Twenty people, one room, one focus session. Full house.',
  },
  // ── Consistency ─────────────────────────────────────────────────────────
  {
    id: 'habit-forming',
    name: 'Habit Forming',
    emoji: '🔥',
    description: 'Complete at least 1 pomodoro on 3 consecutive calendar days.',
    hint: 'Complete at least 1 pomodoro on 3 consecutive calendar days.',
    category: 'consistency',
    tier: 'bronze',
    isSecret: false,
    progressType: 'count',
    progressTarget: 3,
    toastCopy: 'Three days in a row. A habit is starting to form.',
  },
  {
    id: 'week-in-the-zone',
    name: 'Week in the Zone',
    emoji: '📅',
    description: 'Complete at least 1 pomodoro on 7 consecutive calendar days.',
    hint: 'Complete at least 1 pomodoro on 7 consecutive calendar days.',
    category: 'consistency',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 7,
    toastCopy: 'Seven days straight. You\'ve completed your first week. That\'s no accident.',
  },
  {
    id: 'unbreakable',
    name: 'Unbreakable',
    emoji: '💎',
    description: 'Complete at least 1 pomodoro on 30 consecutive calendar days.',
    hint: 'Complete at least 1 pomodoro on 30 consecutive calendar days.',
    category: 'consistency',
    tier: 'gold',
    isSecret: false,
    progressType: 'count',
    progressTarget: 30,
    toastCopy: 'Thirty days without missing one. You built something real.',
  },
  {
    id: 'centurion-streak',
    name: 'Centurion Streak',
    emoji: '🌟',
    description: 'Complete at least 1 pomodoro on 100 consecutive calendar days.',
    hint: 'Complete at least 1 pomodoro on 100 consecutive calendar days.',
    category: 'consistency',
    tier: 'platinum',
    isSecret: false,
    progressType: 'count',
    progressTarget: 100,
    toastCopy: 'One hundred days. Whatever you\'re working on, you\'re going to finish it.',
  },
  {
    id: 'creature-of-habit',
    name: 'Creature of Habit',
    emoji: '⏰',
    description: 'Complete pomodoros starting in the same 2-hour time window on 10 different days.',
    hint: 'Complete pomodoros starting in the same 2-hour time window on 10 different days.',
    category: 'consistency',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 10,
    toastCopy: 'Same time, ten different days. Your brain knows when it\'s time to work.',
  },
  {
    id: 'weekend-warrior',
    name: 'Weekend Warrior',
    emoji: '⚔️',
    description: 'Complete 5 pomodoros on a single Saturday or Sunday.',
    hint: 'Complete 5 pomodoros on a single Saturday or Sunday.',
    category: 'consistency',
    tier: 'bronze',
    isSecret: false,
    progressType: 'count',
    progressTarget: 5,
    toastCopy: 'Five sessions on a weekend. Your future self thanks you.',
  },
  {
    id: 'perfect-week',
    name: 'Perfect Week',
    emoji: '✅',
    description: 'Complete 4+ pomodoros every day for 7 consecutive days.',
    hint: 'Complete 4+ pomodoros every day for 7 consecutive days.',
    category: 'consistency',
    tier: 'gold',
    isSecret: false,
    progressType: 'binary',
    toastCopy: 'Four or more, every single day, for seven days. That\'s not a week — that\'s a statement.',
  },
  {
    id: 'study-buddy',
    name: 'Study Buddy',
    emoji: '📚',
    description: 'Complete a pomodoro in a room with the same friend on 5 different calendar days.',
    hint: 'Complete a pomodoro in a room with the same friend on 5 different calendar days.',
    category: 'consistency',
    tier: 'silver',
    isSecret: false,
    progressType: 'count',
    progressTarget: 5,
    toastCopy: 'Five days focusing alongside the same friend. You two make a good team.',
  },
  // ── Easter Eggs ─────────────────────────────────────────────────────────
  {
    id: 'pomversary',
    name: 'Pomversary',
    emoji: '🎂',
    description: 'Complete a pomodoro within 7 days of your 1-year account anniversary.',
    hint: 'Complete a pomodoro within 7 days of your 1-year account anniversary.',
    category: 'easter_egg',
    tier: 'gold',
    isSecret: true,
    progressType: 'binary',
    toastCopy: 'One year with PomoPals. Whatever you\'ve been building — you\'ve been building it for a year now.',
  },
  {
    id: 'back-from-the-dead',
    name: 'Back From the Dead',
    emoji: '💀',
    description: 'Complete a pomodoro after being away from PomoPals for 30+ days.',
    hint: 'Complete a pomodoro after being away from PomoPals for 30+ days.',
    category: 'easter_egg',
    tier: 'silver',
    isSecret: true,
    progressType: 'binary',
    toastCopy: 'Thirty days away. But here you are. Welcome back — the timer was waiting.',
  },
];

export const ACHIEVEMENT_MAP = new Map<string, AchievementDefinition>(
  ACHIEVEMENTS.map((a) => [a.id, a])
);
